using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;
using UnityEngine;
using Assets._Project.Scripts.Gameplay.EntitiesCore;

public static class EntityApiGenerator
{
    private const string OutputRelativePath = "_Project/Scripts/Gameplay/EntitiesCore/Generated/EntityAPI.g.cs";

    [MenuItem("Tools/ECS/Generate Entity API")]
    public static void Generate()
    {
        Type entityType = typeof(Entity);
        string entityNamespace = entityType.Namespace;
        string entityName = entityType.Name;

        Assembly assembly = entityType.Assembly;
        Type componentInterface = typeof(IEntityComponent);

        Type[] componentTypes = assembly
            .GetTypes()
            .Where(t =>
                t.IsClass &&
                t.IsAbstract == false &&
                componentInterface.IsAssignableFrom(t) &&
                t != entityType)
            .OrderBy(t => t.Name)
            .ToArray();

        var sb = new StringBuilder(16_384);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Этот файл сгенерирован автоматически. Лучше не трогать руками.");
        sb.AppendLine();

        sb.AppendLine($"namespace {entityNamespace}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {entityName}");
        sb.AppendLine("    {");

        for (int i = 0; i < componentTypes.Length; i++)
        {
            Type componentType = componentTypes[i];

            string componentTypeName = GetTypeName(componentType);
            string baseName = RemoveSuffix(componentType.Name, "Component");

            // 1) Доступ к компоненту
            string componentPropertyName = baseName + "Component";
            sb.AppendLine($"        public {componentTypeName} {componentPropertyName} => GetComponent<{componentTypeName}>();");

            FieldInfo[] fields = componentType.GetFields(BindingFlags.Instance | BindingFlags.Public);

            // 2) Если у компонента одно поле Value — генерим “короткую” property и Add
            if (fields.Length == 1 && fields[0].Name == "Value")
            {
                FieldInfo valueField = fields[0];
                string valueTypeName = GetTypeName(valueField.FieldType);

                sb.AppendLine($"        public {valueTypeName} {baseName} => {componentPropertyName}.Value;");

                // Add с готовым value
                sb.AppendLine($"        public {GetTypeName(entityType)} Add{baseName}({valueTypeName} value) => " +
                              $"AddComponent(new {componentTypeName} {{ Value = value }});");

                // Если Value = ReactiveVariable<T> — добавим удобный Add со стартовым значением T
                if (IsReactiveVariable(valueField.FieldType, out Type argType))
                {
                    string argTypeName = GetTypeName(argType);
                    string reactiveTypeName = GetTypeName(valueField.FieldType);

                    sb.AppendLine($"        public {GetTypeName(entityType)} Add{baseName}({argTypeName} startValue) => " +
                                  $"AddComponent(new {componentTypeName} {{ Value = new {reactiveTypeName}(startValue) }});");
                }
            }
            else if (fields.Length > 0)
            {
                // 3) Если полей несколько — генерим Add со всеми полями
                string parameters = string.Join(", ", fields.Select(f => $"{GetTypeName(f.FieldType)} {ToCamel(f.Name)}"));
                string initializer = string.Join(", ", fields.Select(f => $"{f.Name} = {ToCamel(f.Name)}"));

                sb.AppendLine($"        public {GetTypeName(entityType)} Add{baseName}({parameters}) => " +
                              $"AddComponent(new {componentTypeName} {{ {initializer} }});");
            }
            else
            {
                // 4) Если полей нет — Add без параметров
                sb.AppendLine($"        public {GetTypeName(entityType)} Add{baseName}() => AddComponent(new {componentTypeName}());");
            }

            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        string fullPath = Path.Combine(Application.dataPath, OutputRelativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(fullPath));
        File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);

        AssetDatabase.Refresh();
        Debug.Log($"Entity API generated: {fullPath}");
    }

    private static string RemoveSuffix(string name, string suffix)
    {
        return name.EndsWith(suffix, StringComparison.Ordinal)
            ? name.Substring(0, name.Length - suffix.Length)
            : name;
    }

    private static string ToCamel(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static bool IsReactiveVariable(Type type, out Type argType)
    {
        // ReactiveVariable<T> у тебя в глобальном namespace, но по отражению это всё равно один тип.
        if (type.IsGenericType && type.GetGenericTypeDefinition().Name.StartsWith("ReactiveVariable`", StringComparison.Ordinal))
        {
            argType = type.GetGenericArguments()[0];
            return true;
        }

        argType = null;
        return false;
    }

    private static string GetTypeName(Type type)
    {
        // Делаем "global::" имена и нормальные дженерики без мусора от Reflection
        if (type.IsGenericType)
        {
            Type genericDef = type.GetGenericTypeDefinition();
            string defName = genericDef.FullName ?? genericDef.Name;
            int tick = defName.IndexOf('`');
            if (tick >= 0)
                defName = defName.Substring(0, tick);

            string args = string.Join(", ", type.GetGenericArguments().Select(GetTypeName));
            return $"global::{defName}<{args}>";
        }

        string fullName = type.FullName ?? type.Name;
        return $"global::{fullName}";
    }
}